# Generated by Django 6.1.1 on 2026-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyanalysis',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyanalysis',
            name='bmi_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
