# Generated by Django 6.1.1 on 2026-09-20 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0002_bodyanalysis_bmi_bodyanalysis_bmi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
