# Generated by Django 6.1.1 on 2026-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0003_bodyanalysis_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyanalysis',
            name='blood_sugar_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bodyanalysis',
            name='cholesterol_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
